apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pd68765dh-go
  janus-idp.io/tekton: pd68765dh-go
  backstage.io/kubernetes-id: pd68765dh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pd68765dh-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
