apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pd68765dh-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pd68765dh-go 
  name: pd68765dh-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pd68765dh-go 
